### ISSUE TITLE
Maybe you're interested for my repos

### ISSUE THREAD

**Issue by bigbigmdm** [YTEC-info/CH341A-Softwares#5] opened 2024-03-28 10:24 UTC
To add to your file collection:
[IMSProg programmer](https://github.com/bigbigmdm/IMSProg)
[Performance of chip_programmers](https://github.com/bigbigmdm/Performance_of_chip_programmers)
[Tools for the CH341A](https://github.com/bigbigmdm/Tools_for_CH341A_programmer/tree/main)
[Beta CH347 GUI programmer](https://github.com/bigbigmdm/CH347_GUI_SPI_NOR_Flash_programmer)

**Comment by YTEC-info** [comment] 2024-07-18 09:58
Thank you for developing these softwares! It's good to have a graphical interface, many people are afraid of the terminal :P

I tested IMSProg, for some reason when the erase action is performed the system understands that the program has crashed (pic), but it continues to work normally and the dialog box disappears after finishing erasing the chip. The program works normally and well (I'm using the version 1.4.2, Debian 12, GNOME 43.9, Kernel 6.1.0-22)
I will add and reference your repositories. Thank you very much!
![Captura de tela de 2024-07-17 01-17-19](https://github.com/user-attachments/assets/b10e8a30-ab2b-407b-8f60-2ac8efd517d6)

**Comment by bigbigmdm** [comment] 2024-07-18 11:29
Hi, @YTEC-info ! I've seen one similar comment before, but forgot about it. I'm using Linux Mint 21.2 (Victoria) based on Ubuntu 22.04 Jammy Jellyfish (Kernel 5.15.0-87-generic) and testing full reading/erasing/winting cycle on Fedora 38, RedOS 7.3. So far I have not encountered this error. Now I will try to test it on Debian LiveCD. I don't know how to model its occurrence yet.

Could you please advise how many seconds does the formatting take?

**Comment by bigbigmdm** [comment] 2024-07-18 12:56
I just tested in Debian 12 (Bookworm) + XFCE Kernel 6.1.0-18-amd64, Winbond 25Q64BV chip. This problem did not manifest itself. This is very strange! 

P.S. See also reverse engineering programmer CH347 - [here](https://oshwlab.com/einkreader/ch347t-v1-0).

**Comment by bigbigmdm** [comment] 2024-07-18 13:43
It may be correct not to use the CHIP_FULL_ERASE procedure (0xC7 / 0x60), but to use the BLOCK_ERASE procedure sequence (0xD8).

@YTEC-info : If I change the algorithm in this way, will you be able to build and test the new version from source code on your computer?

**Comment by YTEC-info** [comment] 2024-07-19 05:32
> Could you please advise how many seconds does the formatting take?

Formatting takes 20 seconds (W25Q64BV). This is the time that the error window appears and disappears.

> P.S. See also reverse engineering programmer CH347 - [here](https://oshwlab.com/einkreader/ch347t-v1-0).

Excellent, it seems more practical than the CH347 I have (I make the chip connections on a breadboard)

> If I change the algorithm in this way, will you be able to build and test the new version from source code on your computer?

Yes, I can build.

**Comment by YTEC-info** [comment] 2024-07-19 11:14
@bigbigmdm This error message only appears in Gnome! I tested on LXDE, XFCE, Cinnamon and openbox and couldn't reproduce the same problem.

I also tested it on debian trixie/sid and it seems more stable, the message appeared a few times, while on debian stable it appears 100% of the time. (I tested with chips W25Q64, W25Q128)

**Comment by bigbigmdm** [comment] 2024-07-19 11:30
@YTEC-info thanks! I tested with W25Q256 in XFCE, but this message didn't appear...

**Comment by bigbigmdm** [comment] 2024-07-24 12:17
Hello, @YTEC-info !
You can check this option:
[with_block_erase.zip](https://github.com/user-attachments/files/16361879/with_block_erase.zip)

(These files should be replaced in `IMSProg_programmer`). 

I don't know how to work with large (25Q256 / 25Q512) chips yet.  They don't want to erase. If this program works fine on your computer, I will try to finish working with large chips.

**Comment by bigbigmdm** [comment] 2024-07-25 12:05
Hello, @YTEC-info!
Please test on a Gnome desktop with these changes: 
[with_block_erase.zip](https://github.com/user-attachments/files/16377150/with_block_erase.zip)
I tested them for 25q32 and 25Q256 (big chip). Everything is great!
Please replace the files from the archive in the `IMSProg_programmer` folder and run ./build_all.sh

If everything is ok, I will commit these changes to my repository.

**Comment by YTEC-info** [comment] 2024-07-27 02:59
@bigbigmdm Yes, it is now fixed! Tested on the same Debian 12 I reported earlier

**Comment by bigbigmdm** [comment] 2024-07-28 11:17
@YTEC-info , thank you! New release - v1.4.3.

**Closed as completed** 2024-08-15 00:34 UTC
